spring:
    application:
        name: pet-management-service

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    flyway:
        enabled: true
        locations: classpath:db/migration  # Corrigido para o diretório padrão de migração
        baseline-on-migrate: true
        validate-on-migrate: false
