openapi: 3.0.0
info:
  title: "Pet Management Service API"
  description: "API para gerenciar pets e agendamentos de serviços em petshops."
  version: 1.0.0
servers:
  - url: "http://localhost:8080/api/v1"
    description: "Servidor de desenvolvimento"

paths:
  /pets:
    get:
      summary: "Listar todos os pets"
      tags:
        - Pet
      responses:
        '200':
          description: "Lista de pets retornada com sucesso."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: "Cadastrar um novo pet"
      tags:
        - Pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: "Pet cadastrado com sucesso."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

  /pets/{id}:
    get:
      summary: "Obter detalhes de um pet específico"
      tags:
        - Pet
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do pet que será retornado."
      responses:
        '200':
          description: "Pet encontrado."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: "Pet não encontrado."
    put:
      summary: "Atualizar informações de um pet"
      tags:
        - Pet
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do pet que será atualizado."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: "Pet atualizado com sucesso."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: "Pet não encontrado."
    delete:
      summary: "Deletar um pet"
      tags:
        - Pet
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do pet que será deletado."
      responses:
        '204':
          description: "Pet deletado com sucesso."
        '404':
          description: "Pet não encontrado."

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
          description: "ID do pet."
        name:
          type: string
          description: "Nome do pet."
        breed:
          type: string
          description: "Raça do pet."
        age:
          type: integer
          description: "Idade do pet em anos."
        additionalInfo:
          type: string
          description: "Informações adicionais sobre o pet."