openapi: 3.0.0
info:
  title: "Pet Management Service API"
  description: "API para gerenciar pets e agendamentos de serviços em petshops."
  version: 1.0.0
servers:
  - url: "http://localhost:8080/api/v1"
    description: "Servidor de desenvolvimento"

paths:
  /pets:
    get:
      summary: "Listar todos os pets"
      responses:
        '200':
          description: "Lista de pets retornada com sucesso."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: "Cadastrar um novo pet"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: "Pet cadastrado com sucesso."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
  
  /pets/{id}:
    get:
      summary: "Obter detalhes de um pet específico"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do pet que será retornado."
      responses:
        '200':
          description: "Pet encontrado."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: "Pet não encontrado."
    put:
      summary: "Atualizar informações de um pet"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do pet que será atualizado."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: "Pet atualizado com sucesso."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: "Pet não encontrado."
    delete:
      summary: "Deletar um pet"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do pet que será deletado."
      responses:
        '204':
          description: "Pet deletado com sucesso."
        '404':
          description: "Pet não encontrado."

  /appointments:
    post:
      summary: "Agendar um serviço para um pet"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: "Agendamento criado com sucesso."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
  
  /appointments/{id}:
    get:
      summary: "Obter detalhes de um agendamento específico"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do agendamento que será retornado."
      responses:
        '200':
          description: "Agendamento encontrado."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: "Agendamento não encontrado."
    delete:
      summary: "Cancelar um agendamento"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID do agendamento que será cancelado."
      responses:
        '204':
          description: "Agendamento cancelado com sucesso."
        '404':
          description: "Agendamento não encontrado."

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
          description: "ID do pet."
        name:
          type: string
          description: "Nome do pet."
        breed:
          type: string
          description: "Raça do pet."
        age:
          type: integer
          description: "Idade do pet em anos."
        additionalInfo:
          type: string
          description: "Informações adicionais sobre o pet."

    Appointment:
      type: object
      properties:
        id:
          type: string
          description: "ID do agendamento."
        petId:
          type: string
          description: "ID do pet relacionado ao agendamento."
        service:
          type: string
          description: "Serviço agendado (ex: banho, tosa)."
        appointmentDate:
          type: string
          format: date-time
          description: "Data e hora do agendamento."
        status:
          type: string
          description: "Status do agendamento (ex: agendado, cancelado)."
